### ISSUE TITLE
doubleclick gets Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by johanbrunius** [sim51/tank-browser#1]
Hi,

If I doubleclick an node, I get this error, can you please guide me in the right direction?

XMLHttpRequest cannot load http://localhost:7474/db/data/transaction/commit. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8001' is therefore not allowed access. The response had HTTP status code 401.

Kind regards

**Comment by johanbrunius** [comment]
Perhaps should mention, that I did use gulp to "compile" it, so I am not using the "precompiled" version.

**Comment by johanbrunius** [comment]
Nevermind I solved it :)

**Comment by sim51** [comment]
Hi,

Thanks for your issue (you are the first ^^).

In fact there was an issue into the discover module. I have corrected it.

Cheers

**Comment by johanbrunius** [comment]
:)

I saw that it didnt do the autorization correct and fixed it. Thanks for comming back to me in such a short time.

Have you thought about integrating lincururios lasso plugin?

**Comment by sim51** [comment]
Indeed, it could be cool to select & move multiple nodes.
If you have other idea, you can create an issue, I will tag it as "evolution".

Cheers

**Comment by johanbrunius** [comment]
Finding shortest pach, export part of grafs, save grafs, resume grafs, more
visible options for nodes (images, piecharts, etc etc). Having forceatlas2
for new nodes being imported when doubleclick, rightclick nodes for
diffrent kinds of cypher querys, adding autoindent in codewarrior, read in
csv files, show error when something wrong in query, being able to choose
canvas/svg/webgl...etc..etc..  :)

I really like the tank browser and I think it could be a great tool :)
